version: '2'

services:
  warehouse_web:
    build: ./warehouse
    command: bash -c "cd warehouse && gunicorn api.wsgi --bind 0.0.0.0:80 --reload"
    volumes:
      - .:/code
    ports:
      - 80:80
    restart: always
