version: '2'

services:
  warehouse_web:
    build: ./warehouse
    command: bash -c "python warehouse/manage.py runserver 0.0.0.0:80"
    volumes:
      - .:/code
    ports:
      - 80:80
    restart: always
